# config.yaml - Configuration for Guardian Security Gateway

general:
  gateway_name: "Guardian Gateway"
  version: "1.0.0"
  listen_address: "0.0.0.0"
  listen_port: 8080

access_control:
  enabled: true
  allowed_ips:
    - "192.168.1.10"
    - "192.168.1.11"
  blocked_ips:
    - "192.168.1.100"
    - "192.168.1.101"

redirection:
  enabled: true
  rules:
    - name: "Redirect HTTP to HTTPS"
      source_port: 80
      destination_port: 443
      action: "redirect"
    - name: "API Redirection"
      source_path: "/api/v1/*"
      destination_path: "/api/v2/"
      action: "redirect"