# config.yaml - Configuration for Guardian Security Gateway

general:
  gateway_name: "Guardian Gateway"
  version: "1.0.0"
  listen_address: "0.0.0.0"
  listen_port: 8080

access_control:
  enabled: true
  allowed_ips:
    - "192.168.1.10"
    - "192.168.1.11"
  blocked_ips:
    - "192.168.1.100"
    - "192.168.1.101"

redirection:
  enabled: true
  rules:
    - name: "Redirect HTTP to HTTPS"
      source_port: 80
      destination_port: 443
      action: "redirect"
    - name: "API Redirection"
      source_path: "/api/v1/*"
      destination_path: "/api/v2/"
      action: "redirect"

load_balancing:
  enabled: true
  strategy: "round_robin"
  servers:
    - address: "192.168.2.20"
      port: 8081
    - address: "192.168.2.21"
      port: 8081
    - address: "192.168.2.22"
      port: 8081

logging:
  enabled: true
  log_level: "info"
  log_file: "/var/log/guardian/guardian.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_rotation:
    enabled: true
    max_size: 10MB
    backup_count: 5

security:
  rate_limiting:
    enabled: true
    max_requests_per_minute: 100
    ban_duration: 300  # in seconds

  waf:
    enabled: true
    rules:
      - name: "Block SQL Injection"
        pattern: "SELECT|UPDATE|DELETE|INSERT"
        action: "block"
      - name: "Block XSS"
        pattern: "<script>"
        action: "block"

  session_management:
    enabled: true
    session_timeout: 1800  # 30 minutes in seconds
